server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

logging:
  level:
    root: info

spring:
  application:
    name: predictive-portfolio-dev
  config:
    import: optional:classpath:dev.env.properties
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase/master.xml
    enabled: false
  profiles:
    active: @spring.profiles.active@

token:
  registration:
    duration: P1D

url:
  service: http://localhost:8080
  finish-registration: ${url.service}/auth/register/%s
