server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

logging:
  level:
    root: info

spring:
  application:
    name: predictive-portfolio-dev
  config:
    import: classpath:dev.env.properties
  datasource:
    url: ${DB_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  liquibase:
    change-log: classpath:db/liquibase/master.xml
  profiles:
    active: @spring.profiles.active@
